### PR TITLE
Embedded jdk

### PR DESCRIPTION
**Pull request by judovana**
If itw is built in EMBEDDED mode, then it search for jre/jdk "where it is placed" right after java_home.
It is done by simple .., ../..
The search for libraries is then done in same way as for BUNDLED mode

### CODE REVIEW

**Comment by karianna** [comment]
@douph1 Can yo also comment?  I've added you to the team

**Comment by douph1** [comment]
LGTM

**Comment by judovana** [comment]
Thanx douph.  The documentation of BUNDLED, DISTRIBUTION and EMBEDDED should be documented. however, it is for default launchers only.  What about README.md in the launchers folder?

**Comment by karianna** [comment]
> Thanx douph. The documentation of BUNDLED, DISTRIBUTION and EMBEDDED should be documented. however, it is for default launchers only. What about README.md in the launchers folder?

Sounds good to me

**Pull request merged**
