### PR TITLE
decouple deployment configuration from legacy and swing dependency

### PR DESCRIPTION
**Pull request by AndreasEhret**
- decouple deployment configuration from legacy migration (v1.4 and older structures to v1.5)
- decouple deployment configuration from swing dependency

### CODE REVIEW

**Comment by judovana** [comment]
Unless you wish to completly remove this code, ok to merge.

**Comment by AndreasEhret** [comment]
So you wouldn't mind to remove this legacy prior to 1.4 -> 1.5 directory structure migration? Then we should indeed consider to remove this code parts (MigrationUtils content) for 2.0

**Comment by AndreasEhret** [comment]
I've marked the MigrationUtils as deprecated.

**Comment by AndreasEhret** [comment]
As result of our confcall I will remove the legacy code parts for this PR.

**Pull request merged**
