### PR TITLE
remove PluginBrige and all code which becomes unreachable by doing so

### LINKED ISSUE #333: with applet gone remove --html
This swithc have become useless, even worse, will end in error. The switch and its impl should be gone

### PR DESCRIPTION
**Pull request by sclassen**
fixes #333

### CODE REVIEW

**Comment by judovana** [comment]
hi! applet-desc still keeps working right?
One  nit - applets, unlike regular javaws were able to load .class direclty.  I'm not sure uf applet-desc should support it. if not, this possible hole hsould be gone from jnlpclasslaoder to.

**Comment by judovana** [comment]
There were added several integration tests with appelt-desc recently. Can you rebase and trry?

**Comment by sclassen** [comment]
Merged master back into this branch.
But do not rush merging this, I will give it also another thought

**Comment by sclassen** [comment]
@judovana 
I looked at it again and it seems reasonable for me. Especially since the entire applet part has been removed from Java11...
So everybody who needs applet must stay on a java version before 11 and can therefore use the Oracle Web Start if they want to

**Comment by judovana** [comment]
yup. ok to go the, TY!

**Pull request merged**
