### PR TITLE
Support for windows system proxy

### PR DESCRIPTION
**Pull request by hendrikebbers**

### CODE REVIEW

**Comment by janakmulani** [comment]
Windows Proxy Server setting: 'localhost:3128'
Windows Proxy Server override hosts setting: '*.local'
proxysetting

**Comment by janakmulani** [comment]
Windows Proxy Server setting: 'localhost:3128'
Windows Proxy Server override hosts setting: '*.local'
proxydisabled

**Comment by janakmulani** [comment]
Windows Proxy Server setting: 'http=localhost:3128;https=localhost:3129;ftp=localhost:3130;socks=localhost:3131'
Windows Proxy Server override hosts setting: '*.local;*.karakun'
AdvProxySetting
AdvProxySetting2

**Comment by janakmulani** [comment]
Proxy from Script:
Windows Proxy Server setting: 'http=localhost:3128;https=localhost:3129;ftp=localhost:3130;socks=localhost:3131'
Windows Proxy Server override hosts setting: '*.local;*.karakun'
ProxyFromScript

**Comment by hendrikebbers** [comment]
https://github.com/devjta/java-registry/blob/master/src/at/jta/Regor.java

**Comment by hendrikebbers** [comment]
http://www.davidc.net/programming/java/reading-windows-registry-java-without-jni

**Comment by patris70** [comment]
maybe we can using too:

                if ((proxyServer.startsWith("ftp=")) || (proxyServer.startsWith("http=")) || (proxyServer.startsWith("https=")) || (proxyServer.startsWith("socks="))) {
				proxyServer = proxyServer.replaceAll("\\.*.*=" , "").replaceAll(";.*" , "");
				}
				else {
				 proxyServer = proxyServer;
				}

> 
> 
> Proxy from Script:
> Windows Proxy Server setting: 'http=localhost:3128;https=localhost:3129;ftp=localhost:3130;socks=localhost:3131'
> Windows Proxy Server override hosts setting: '_.local;_.karakun'
> ProxyFromScript

**Comment by hendrikebbers** [comment]
Java WindowsPreferences can not read DWORD... See
https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.prefs/windows/native/libprefs/WindowsPreferences.c

Line 138-following:
```
jbyteArray result;
    if (valueType == REG_SZ) {
        result = (*env)->NewByteArray(env, valueSize);
        if (result != NULL) {
            (*env)->SetByteArrayRegion(env, result, 0, valueSize, buffer);
        }
    } else {
        result = NULL;
    }
```

**Comment by patris70** [comment]
@hendrikebbers 
i sended PowerShell command in java code per Email.
Why do you not using PowerShell injava code?

Regards

**Comment by hendrikebbers** [comment]
@patris70 I have no idea if `reg query` or `powershell` is better. Are both available on all windows versions?

**Comment by patris70** [comment]
@hendrikebbers,

absolutely PowerShell, because is faster, more Options or function and you have more choice and scopes.

For example if you using PowerShell, you do not need using reg.exe because with PowerShell you can get every info from Registry or Windows OS information but with Dos ( i mean cmd.exe you must using different EXE files to get infos.

Hope to help
Regards

**Comment by patris70** [comment]
@hendrikebbers 

any news or updates?

**Pull request merged**
