### PR TITLE
applet functionality removed

### PR DESCRIPTION
**Pull request by hendrikebbers**
This removes support for applets at several places.

### CODE REVIEW

**Comment by judovana** [comment]
hi!

Most of ths is correct. Only ... <applet-desc> should be kept supported. Can it be? This patch is removing also tat, isnt it?

**Comment by hendrikebbers** [comment]
What do you mean with "..."?

**Comment by judovana** [comment]
Arg :D  md syntax consumed it! it was applet-desc element. ```<applet-desc>``` is shown as ...

**Comment by hendrikebbers** [comment]
ok, I will have a look :)

**Comment by hendrikebbers** [comment]
I think I need to understand better what `<applet-desc>` really does in a JNLP. So let's shift this discussion to the next days :)

**Comment by judovana** [comment]
> I think I need to understand better what `<applet-desc>` really does in a JNLP. So let's shift this discussion to the next days :)

Ok.  Are you already avare of appelt desc?-) Whats the result?

**Comment by judovana** [comment]
if both application-desc and applet-desc  in jnlp works,  dont hesitate to push!

**Comment by judovana** [comment]
ih. plerase remove --html switch and its handling

**Pull request closed without merging**
