### PR TITLE
Forced recognition of system jars

### PR DESCRIPTION
**Pull request by mpritt**
Attempting to use built in java security packages when running java web start applications results in permission denials.  These permission denials occur upon initialization of the packages for sun security such as mscapi and jgss.    Even though an application has been allowed to run with all permissions, these packages were being denied runtime and security permissions.   Output for these denials are shown below: 

Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying permission: ("java.security.SecurityPermission" "putProviderProperty.XMLDSig")
Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying permission: ("java.lang.RuntimePermission" "accessClassInPackage.sun.security.util")
Denying permission: ("java.lang.RuntimePermission"  "loadLibrary.sunmscapi")
Denying permission: ("java.util.PropertyPermission"  "sun.security.jgss.native" "read")

### CODE REVIEW

**Comment by karianna** [comment]
@mpritt I assume this is with 1.8.1?

**Comment by mpritt** [comment]
Yes, actually I've tested with 1.7.x and on up with the exception of the master.  I've not tried with code from the master but looking at it I would imagine the same problem existing there.

**Comment by mpritt** [comment]
This seems to be the right fix from my testing and in light of this document:  http://openjdk.java.net.jeps/220 .  As other changes go in to the main JDK in the future, this may no longer be needed.  On a side note...we've used the original javaws for many years not having any problems.  However once we switched to icedtea-web, those permission denials occurred.

**Comment by mpritt** [comment]
Sorry, I typed in the wrong link, here is the correct one: http://openjdk.java.net/jeps/220

**Comment by judovana** [comment]
This looks good to me to. Please fix the codestyle from c one to java oe (the block bracket should go behind the if brackets).  Please ensure you propose also backport PR after this one.
Please note, 1.7 in this repo is broken. I keep posting the author, but he most likely died or simply disapeared.
Generally 1.7 is dead. I doubt any 1.7 will be released ever.

**Comment by mpritt** [comment]
This fix should also be back ported to 1.8.x as well.

**Comment by mpritt** [comment]
Not sure how to create a backport PR.  I can see the PR closed as the code was merged into the master.  So can you give me the steps for doing a backport PR?  I’m fairly new to git, not having worked with it much.

thanks

**Comment by sclassen** [comment]
@mpritt I did the backport. Thx for your PR

**Pull request merged**
