### PR TITLE
JNLP servlet module added

### PR DESCRIPTION
**Pull request by hendrikebbers**
Module taken as copy from https://github.com/mojohaus/webstart

### CODE REVIEW

**Comment by judovana** [comment]
Hmm. What is this? Why so?-)
Why copypaste it and not include it?

**Comment by hendrikebbers** [comment]
@judovana hope this answer your questions :)

The new module is a copy of the JNLP-servlet-lib that was provided several years ago by SUN. 
Codehaus / Mojohaus copied the sources from SUN an added them to the https://github.com/mojohaus/webstart repo.

The code contains several useful classes for JarDiff, versioning since this is de facto the lib that everyone uses on server side to offer JNLPs (that use such features). @AndreasEhret is currently working on the version, jar-version, ... classes in this repo and we thought that it would make sense to share util classes between both sides (JNLP generation on the server - JNLP parsing on the client). Next to this the server lib is still in a beta release status and we at Karakun would love to provide a supported version of the lib. Therefore we thought it would be a good idea to add it directly to the repository.

**Comment by judovana** [comment]
I see. Then the incorporation is ok, but copying? It od nothave sense. the mojohouse/webstart is in central repo. I think it is better to depend on it.  It is no obstacle to support. You can stil contribute to mojohouse directly. 
Even forking this project is still better then hardcode copy (sorry:( )

**Comment by hendrikebbers** [comment]
@judovana unterstand that. But If we want to share / reuse classes in both modules (ITW and Servlet) it is much faster to a refactoring here. Later everything can be contributed to Mojohouse as a PR (with an internal dependency to ICT-common since classes are shared).

**Comment by hendrikebbers** [comment]
If if Mojohouse accept the PR we can delete the module here.

**Comment by judovana** [comment]
I see. I think this can not be alive without support of mojohouse. Is the PR already here?

**Comment by judovana** [comment]
To lower the requirement - If people deploy  jnlp servlet from mojohous, will ITW collaborate without issues with it?
As the idea of shared logic is really god, I do not wont to kill the PR

**Comment by AndreasEhret** [comment]
we should take this in for now and see how we can make best use of it.

**Comment by judovana** [comment]
I keep wondering what it will be used for...
Was  mojohouse at least notified about the need for changes?

**Pull request merged**
