### PR TITLE
Initial Maven Setup

### LINKED ISSUE #20: provide Maven based project definition
We want to refactor the Java part of this project to Maven

### PR DESCRIPTION
**Pull request by hendrikebbers**
This PR will fix #20 #21 and #22 

This is a quite big PR but top be true I have no idea how this could be split down to several Pos...
The PR includes the following changes:

- All native parts and the sources of the applet plugin are removed
- `make` based build is removed
- project is based on Maven
- All test that do not work on my system are annotated by `@Ignore`
- `.gitignore` created based on the current structure
- `readme` is removed since the content is not valid anymore
- eclipse settings removed

### CODE REVIEW

**Comment by hendrikebbers** [comment]
I think the best way to review this PR is to checkout the branch and open it in any IDE

**Comment by hendrikebbers** [comment]
@judovana I would love to create an issue for a README.md and do it in a separate PR later this week. This is already way to big.

**Comment by hendrikebbers** [comment]
issue created #24

**Comment by hendrikebbers** [comment]
The often end with timeouts and it was not really reproduceable. First I added `@Ignore` to only some but than in the second run others were failing (timeout). Based on this I decided to add `@Ignore` at class level.

**Comment by judovana** [comment]
I see. You run them on mac, right?   So we can at least assume that splash is  a bit unstable on mac.   Btt really can be caused by wrongtests

**Comment by hendrikebbers** [comment]
@judovana I have only 4% power left on my MacBook and missed to take the power plug with me. Will continue tomorrow

**Comment by hendrikebbers** [comment]
yes, I run them on Mac

**Comment by judovana** [comment]
> I think the best way to review this PR is to checkout the branch and open it in any IDE
Yes. . on some level it come to this :)

**Comment by judovana** [comment]
rhino should be plugin only, isnt it?

**Comment by judovana** [comment]
cpp unit tests can be removed, are plugin only.

**Comment by judovana** [comment]
Once cpp-unittests are gone,  the old-tesuite can be maybe renamed  integration-tests ?
As all the logic which rremianed are reproducers, and codecoverage above reproducers.

**Comment by judovana** [comment]
I'm against  removal of win isntaller, rust launchers and shell launchers.
Even in current setup, they can be easily adapted to use product of the maven run above core.
But that is in direct  alignment with the choice of multi-repo or single repo. I really belive that isnfge repo with several modules is much better. Shell and rust laucnhers are two of modules. Otr submodule si fyou wish. 
maybe
java (top module for all shared java classes0
  - core (module formerer netx)
  - controlpanel - module of current control panel
  -controlpanelFC -module for your new control panel
launchers (top module for launchers)
     - shell
     - rust
     - msi (tbd)

WDYT?

**Comment by judovana** [comment]
the appdata should be preserved. Not sure where to put them
bash completion would go to the launchers module
(??)

**Comment by judovana** [comment]
Desktop in should go to launchers module

**Comment by judovana** [comment]
I guess the generated docs stopped working right now. Is (former) javaws --verbose --about and controlpanel --verbose --about     working for you?

As the docs generation should be only call to the javaws.jar, with creapy main class See (stamps/generate-docs.stamp: stamps/netx.stamp):  ... net.sourceforge.jnlp.util.docprovider.TextsProvider
It is very nice feature.

**Comment by judovana** [comment]
itw-modularjdk.args should be preserved. And they should be actually preerved in the main  core module. But thats on discussion.

**Comment by judovana** [comment]
Generaly. This is grat work. I'm +1 with it. The decision  if the singlerepo-multiproject will beallowed was not yet agreed. 
If not, then Where to move launchers and frieds is an question. My current view is, that it is inseparable part of javaws.  rusr laucnhers, shell launchres, contropl panel, controlpanel fx.. all judt wrappers around core.

**Comment by judovana** [comment]
> yes, I run them on Mac

In maven branch: Failed tests:   testHomeVariable(net.sourceforge.jnlp.util.XDesktopEntryTest): Variable 
...
Tests run: 987, Failures: 1, Errors: 0, Skipped: 35

I'm not sure how to handle platform-specific tests and - more scarry - platfrom specific fails. There hsouldbe none, but then we need paltform sepcific ignore. Any idea?

**Comment by judovana** [comment]
The inegration tests are fll of applets. I'm wondering you did both mavenization and plugin removal in one step. I would chose two, as removal of plgin can be tricky. But I guess you sihed not be bound with make (ok by me, just writing it down)

**Comment by hendrikebbers** [comment]
discussion about split will be continued in #21 since this PR will be merged / closed in future.

**Comment by hendrikebbers** [comment]
@judovana do you think new can merge this for now? I will add some issues to topics that were discussed here (like platform dependent tests)

**Comment by judovana** [comment]
Also optional depndencies are no longer optional. But I guess gentoo can simply patch them out...

**Comment by judovana** [comment]
There was more told in the review.  Eg removal of cpp unittests,  renaming of directory, what to do with optional depndencies,  and fate of some other files.
So maybe jsut put them all to unseorted dir or anything?

**Comment by hendrikebbers** [comment]
About optional dependencies: We can them define as compile only. What dependencies do you mean?

**Comment by hendrikebbers** [comment]
removed CPP tests just now

**Comment by hendrikebbers** [comment]
"renaming of directory" <- would like to discuss this in #21 before doing it

**Comment by hendrikebbers** [comment]
"fate of some other files" <- can you be more concrete

**Comment by judovana** [comment]
If you insits on merging without following any of the nits, it is very Likely my next PR will be return of them. So it si better to settle this now. isnt it?
And I think best would be to keep them in . It is always more easy to delte stuff, then add.

**Comment by judovana** [comment]
> "fate of some other files" <- can you be more concrete

- readme md - canbe postponded for sure
- tests - from my point of view ignore is missing on one test, and soem splash tests are suspicious to fail at your end. Not sure how to deal with those. Mass ignore is probabl best  to start with. But it is suggesting something.
- metadata, bashcomplition and desktop files (aligned with launchers), itw-modularjdk.args  (imho important, and not launchers connected)
- And you have not answered the docs question (but that is also minor)

Sorry for commenting to the PR:-/

**Comment by hendrikebbers** [comment]
THX!
At a customer today but will work on your list later :)

**Comment by hendrikebbers** [comment]
> * readme md - canbe postponded for sure
yes, let's get this PR done as soon as possible. Than we can start with small PRs
> * tests - from my point of view ignore is missing on one test, and soem splash tests are suspicious to fail at your end. Not sure how to deal with those. Mass ignore is probabl best  to start with. But it is suggesting something.
What test should have Ignore in addition? ->  testHomeVariable(net.sourceforge.jnlp.util.XDesktopEntryTest this one?
 Mass ignore is just for now. Once this PR is merged we should discusss how we can handle OS dependent tests
> * metadata, bashcomplition and desktop files (aligned with launchers), itw-modularjdk.args  (imho important, and not launchers connected)
Can you give me a hint where itw-modularjdk.args should be placed in the new folder structure
> * And you have not answered the docs question (but that is also minor)
From my point of view this should be done after this PR since I need more input here.

**Comment by AndreasEhret** [comment]
I realized that some tests are not executed with maven, but are executed when trigger in the IDE. This is because of some of our test classes do not follow the default Maven naming conventions:
- Test*
- *Test
- *TestCase

and therefore did not run so far with your PR maven build.

After renamed (I wanted to stay with the default for now):

ParserCornerCases => ParserCornerCasesTest
JNLPMatcherTestMallformedAllowed => JNLPMatcherTestMallformedAllowedTest
ParserMalformedXml => ParserMalformedXmlTest

I have now some more unit tests executed with the maven build, and also failing ones. I will check in the renamed tests to the pull request

**Comment by hendrikebbers** [comment]
From my point of view we need to handle the following tasks before we can merge this PR:

- [ ] create `launcher` folder as root for all launchers
- [ ] add launchers to `launcher` folder <- For this PR we won't define them as maven modules
- [ ] add  `itw-modularjdk.args`

**Comment by judovana** [comment]
> > "fate of some other files" <- can you be more concrete
> 
>     * readme md - canbe postponded for sure
> 
>     * tests - from my point of view ignore is missing on one test, and soem splash tests are suspicious to fail at your end. Not sure how to deal with those. Mass ignore is probabl best  to start with. But it is suggesting something.
> 
>     * metadata, bashcomplition and desktop files (aligned with launchers), itw-modularjdk.args  (imho important, and not launchers connected)
> 
>     * And you have not answered the docs question (but that is also minor)
> 
> 
> Sorry for commenting to the PR:-/

Oh and COPYING must stay here. And must be renamed to LICENSE see issue#16

**Comment by judovana** [comment]
> I realized that some tests are not executed with maven, but are executed when trigger in the IDE. This is because of some of our test classes do not follow the default Maven naming conventions:
> 
>     * Test*
> 
>     * *Test
> 
>     * *TestCase
> 
> 
> and therefore did not run so far with your PR maven build.
> 
> After renamed (I wanted to stay with the default for now):
> 
> ParserCornerCases => ParserCornerCasesTest
> JNLPMatcherTestMallformedAllowed => JNLPMatcherTestMallformedAllowedTest
> ParserMalformedXml => ParserMalformedXmlTest
> 
> I have now some more unit tests executed with the maven build, and also failing ones. I will check in the renamed tests to the pull request

The @ignore and renaming should not be part of this PR. Test cleanup should be separate PR, but I do not insists.

**Comment by judovana** [comment]
> From my point of view we need to handle the following tasks before we can merge this PR:
> 
>     * [ ]  create `launcher` folder as root for all launchers
> 
>     * [ ]  add launchers to `launcher` folder <- For this PR we won't define them as maven modules

yes, souds good
> 
>     * [ ]  add  `itw-modularjdk.args`

I really am not sure where to put them. Maybe to top/launcher sdirectly? As they are reused by both launchers, an very likley by any other launcher to come

>     * [ ]  copy COPYING to LICENSE
> * []  drop @ignore  ;  it desrves separate changeset

**Comment by AndreasEhret** [comment]
> From my point of view we need to handle the following tasks before we can merge this PR:
> 
>     * [ ]  create `launcher` folder as root for all launchers
> 
>     * [ ]  add launchers to `launcher` folder <- For this PR we won't define them as maven modules
> 
>     * [ ]  add  `itw-modularjdk.args`

and * [ ] fix the broken tests? I've looked into the xml parsing ones but no clue up to know what the problem is. We didn't changed some xml parsing defaults up to now (strict/non-strict, malformed allowed/not allowed)

**Comment by judovana** [comment]
> > From my point of view we need to handle the following tasks before we can merge this PR:
> > ```
> > * [ ]  create `launcher` folder as root for all launchers
> > 
> > * [ ]  add launchers to `launcher` folder <- For this PR we won't define them as maven modules
> > 
> > * [ ]  add  `itw-modularjdk.args`
> > ```
> 
> and * [ ] fix the broken tests? I've looked into the xml parsing ones but no clue up to know what the problem is. We didn't changed some xml parsing defaults up to now (strict/non-strict, malformed allowed/not allowed)

As I wrote, I would leave any test work form this PR. Just copy it as they are, without new ignore, witout new names, witout fixes.

Another PR would be adding @ignore, and fixing name conventions. 

Maybe then there is time to fix something. 
tests for malformed  jnlp depends on tagsoup. But you have tagsoup on in pom... Is it on CP also for tests?
strict/nonstrict should work out of the box.

**Comment by hendrikebbers** [comment]
> As I wrote, I would leave any test work form this PR. Just copy it as they are, without new ignore, witout new names, witout fixes.

No, since this would end in a PR that can not be build. I think it's important that the build is working after the PR.

**Comment by hendrikebbers** [comment]
@judovana tagsoup is on class path for tests

**Comment by AndreasEhret** [comment]
in maven we reference tagsoup 1.2, is this the same as in the make builds? Where do I find the version there?

**Comment by judovana** [comment]
> in maven we reference tagsoup 1.2, is this the same as in the make builds? Where do I find the version there?

that is the same I have forl old make-build.  Maybe it should be on xbootclassapth?  But for unttests it should not meter.

**Comment by AndreasEhret** [comment]
> > As I wrote, I would leave any test work form this PR. Just copy it as they are, without new ignore, witout new names, witout fixes.
> 
> No, since this would end in a PR that can not be build. I think it's important that the build is working after the PR.

I also vote for fixing the tests whereever possible or at least @Ignore with comment after we understood why the suddenly fail.

**Comment by judovana** [comment]
I have made pull of current state:
please rename old-test-suite  to integration-tests
drop authors, chnagelog and news ?
launchers are still missing.

**Comment by judovana** [comment]
Please @ignore also  testHomeVariable if yu wont to make tests fully passable.

**Comment by judovana** [comment]
Then please @ignore also testHomeVariable 
Maybe aslo cosnider @ignore to all @knowntofail

**Comment by AndreasEhret** [comment]
> Oh and COPYING must stay here. And must be renamed to LICENSE see issue#16

renamed. So we do not need COPYING any more, right?

**Comment by judovana** [comment]
> > Oh and COPYING must stay here. And must be renamed to LICENSE see issue#16
> 
> renamed. So we do not need COPYING any more, right?

I'm not sure. Sorry for confussion. Check that files and see on your own.

**Comment by judovana** [comment]
Onesmall nit if I can. Can you rename launcher->launchers? Again., I do not isnists.

**Comment by judovana** [comment]
please drop changelog  and install and news

**Comment by judovana** [comment]
Please copy bash compeltion to launchers

**Comment by judovana** [comment]
please copy metadata.in to launchers

**Comment by judovana** [comment]
metadata in can be dropped later. Currenly I'm just not sure with them.

**Comment by judovana** [comment]
drop the  rhiino from pom? Si there any reason to keep itin I dont know about?

**Comment by judovana** [comment]
Please return win installer to launchers

**Comment by judovana** [comment]
I would proabbly stop complicating licensing. Keep License as you have it - gpl2, and dtop copying.

**Comment by judovana** [comment]
*.desktop.in files into launchers

**Comment by judovana** [comment]
please put javaws.png to launchers

**Comment by judovana** [comment]
Check the netx.manifest.in. Maybe it is something what you wish in pom. I have no preference.

**Comment by judovana** [comment]
is assembly target to be considered ever after? /me jsut curious

**Comment by judovana** [comment]
Thank you very much for keeping all the launcher stuff and few more in the tree.

Please note, that about dialog was partially generated from authors, news and changelog. This is now gone. Not that it wouldbe somehow useful - just letting you know.

I have:
Failed tests:   getMainClassNameTestEmpty(net.sourceforge.jnlp.runtime.JNLPClassLoaderTest): expected:<0> but was:<3>
  constructorFileLeakTest(net.sourceforge.jnlp.runtime.JNLPClassLoaderTest): expected:<0> but was:<10>
  testResourceLoadSuccessCachingApplication(net.sourceforge.jnlp.runtime.CodeBaseClassLoaderTest)
  testHomeVariable(net.sourceforge.jnlp.util.XDesktopEntryTest): Variable home should be declared  before test run, but was not and so is faked. This should be ok and is thrown just for record. See output of ensureHomeVaribale and restoreHomeVaribale expected null, but was:<{}>

Please ignore them too.

How about the conflict github is reporting? I guess that is caused by merge I did today mornig. Can you rebase please?

After that, I'm happy to merge. Do we agree on squash and merge?

**Comment by hendrikebbers** [comment]
`RhinoBasedPacEvaluator` is using `rhino`. Therefore we can not remove this decency for now.

**Pull request merged**
