### PR TITLE
add forkingStrategy

### PR DESCRIPTION
**Pull request by sclassen**
converting the forksAllow to an enum allows for taking care of all possible states.
Also for the ones of OpenWebStart

### CODE REVIEW

**Comment by AndreasEhret** [comment]
nice solution, LGTM

**Comment by judovana** [comment]
Why the conditions in https://github.com/AdoptOpenJDK/IcedTea-Web/pull/404#issuecomment-528322754  are not evaluated?  Anyway thank you for fixing the forking.

**Comment by sclassen** [comment]
this will happen in openwebstart code and we will set the correct strategy on JNLPRuntime

**Comment by judovana** [comment]
hmhhm. ok then.

**Pull request merged**
