### PR TITLE
Adjustments to the msi-installer:

### PR DESCRIPTION
**Pull request by lherschi**
- change from java.bat to java.exe
 - use HKLM\Software\Classes instead of HKCR, as entries are otherwise
   made in HKCU\Software\Classes and then not apply to all users
 - register jnlp-file and jnlps-protocol

### CODE REVIEW

**Comment by hendrikebbers** [comment]
must be reviewed by @judovana 
No idea what this does :D

Maybe merge in 1.8 would be better

**Comment by judovana** [comment]
@hendrikebbers next itw is 1.9 or 2?
@lherschi  - Is it possible to obtain the 1.9.0 numbers from pom somehow? (not that it is now not possible in tip, but work in progress)

**Comment by hendrikebbers** [comment]
2.0 would make sense this we change a lot.

**Comment by judovana** [comment]
> 2.0 would make sense this we change a lot.

agree

**Comment by judovana** [comment]
@lherschi  please update it to 2.0.0 then. TYVM!

**Comment by karianna** [comment]
@judovana AFAIK This PR is against master and therefore is 2.0.x

**Comment by karianna** [comment]
@judovana Is this safe to merge now?

**Pull request merged**
