### PR TITLE
Task #3714 - Packed resources are stored in cache with double file ex…

### PR DESCRIPTION
**Pull request by lherschi**
https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3714

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Hi @lherschi can you add a description or issue link to this PR?
THX

**Comment by lherschi** [comment]
https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3714

**Comment by judovana** [comment]
The description will be duplicated with  content of https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3714 ; So links looks goof, until classapth bugzilla is obsolated. I would follow https://github.com/AdoptOpenJDK/icedtea-web/pull/8, but I do not have strong prefferences.

**Comment by lherschi** [comment]
see new pull request:
https://github.com/AdoptOpenJDK/icedtea-web/pull/12

**Pull request closed without merging**
