### PR TITLE
Backport PR #438: AWTSecurityManager was removed

### PR DESCRIPTION
**Pull request by bourgesl**
See Issue #437 

This is a trivial backport for the branch 1.8 to make icetea-web work on OpenJDK 13 to 17, tested on 15, 16, 17 EA.

### CODE REVIEW

**Comment by bourgesl** [comment]
MacOS builds are broken: automake is missing !

**Comment by bourgesl** [comment]
Please consider integrating this trivial pull request to let work itw 1.8 with openjdk 13-17ea ...

**Comment by bourgesl** [comment]
Anybody can have a look and merge this trivial PR for itw 1.8 ?

**Comment by sclassen** [comment]
We fixed the build problem in 1.8 branch. Can you please rebase/merge your changes to include the most current 1.8 branch.

**Comment by sclassen** [comment]
ping

**Comment by bourgesl** [comment]
Sorry I merged changes in my branch, but it did not trigger any action.
Could you trigger another build ?
I can open another PR or ...what should I do ?

**Comment by sclassen** [comment]
Funny this would usually trigger a new build and it would also show up in this PR view.
I will have a look what is going wrong

**Comment by sclassen** [comment]
ok, closing and re-opening has finally triggerd the build.

**Comment by bourgesl** [comment]
Thanks!

FYI I did use the new Fetch & Merge button on github UI, that caused problems with gh actions, sorry.

**Comment by BSG2000** [comment]
Ich have install the actual Release 1.8.7 but still getting this error. Can someone imagine why?
image

**Comment by bourgesl** [comment]
> Ich have install the actual Release 1.8.7 but still getting this error. Can someone imagine why?
> image

Actually itw 1.8.7 tag was made on may 17th, this patch was integrated on may 27th.
See
https://github.com/AdoptOpenJDK/IcedTea-Web/commits/icedtea-web-1.8.7

@sclassen when is the coming 1.8.8 release including this bug fix ?

**Pull request merged**
