### PR TITLE
merging TIP from release/icedtea-web-1.7

### PR DESCRIPTION
**Pull request by sclassen**

### CODE REVIEW

**Comment by sclassen** [comment]
@judovana can you take a quick look if this import of icedtea-web-7 looks good for you

**Comment by hendrikebbers** [comment]
@judovana should we merge this one now? I have no idea if this reflect the release branch in a right way.

**Comment by judovana** [comment]
Not sure if there is anything worthy for 1.7. Will backport manually.

**Comment by judovana** [comment]
Can this be please reopen?

**Comment by sclassen** [comment]
unfortunately no, as I deleted the repo.
Will create a new PR

**Pull request closed without merging**
