### PR TITLE
Task #3709 - Windows desktop shortcut contains wrong target if javaws.exe is accessible via the path

### PR DESCRIPTION
**Pull request by lherschi**
- findOnPath returns the full path including directory part
- getJavaWsBin now prefers KEY_JAVAWS_LOCATION before the path
- icon from the jnlp file is also used now for desktop and menu entry
- the icon is converted to ico if it is in gif, jpg or png format
- fixes a npe in createWindowsMenu
- menu items can now also be created if it is not intended by the application

https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3709

### CODE REVIEW

**Comment by judovana** [comment]
Hi!

The first commit is doing really a lot of stuff. Can you split it to commit per change?

**Comment by judovana** [comment]
Also the second commit contains two changes, The ":" handling, and exe handling. Again, can you please split it?
Can the ":" handling got tests please?

**Comment by lherschi** [comment]
The first commit is for Bugzilla Task # 3709 and the second commit is for Task # 3711. Every commit in itself is for exactly one topic. I do not know how to separate the content.

**Comment by judovana** [comment]
hi Lars. Can you rebase please? There is going to happen a lot of breaking changes. I will try to merge yours PRs before  those happens

**Comment by judovana** [comment]
I guess this should be closed. INdividual chagesets were discussed, but some more are missing. MAybe new PRs?

**Comment by lherschi** [comment]
Ok, I could divide that into two parts, one for the right target and one for the desktop icon and the menu entry.

**Comment by judovana** [comment]
Can you please rebase tehbranch to currnet tip? The PR like this can notbe reviewed/merged properly ( or I need advice hw to do so).
From what I can see,  it hsould contain 4 related commits. Am I right?

**Comment by lherschi** [comment]
see new pull request:
https://github.com/AdoptOpenJDK/icedtea-web/pull/114

**Pull request closed without merging**
