### PR TITLE
Task #3715 - Packed resources are unnecessarily cached after unpacking

### PR DESCRIPTION
**Pull request by lherschi**
https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3715

### CODE REVIEW

**Comment by hendrikebbers** [comment]
Hi @lherschi can you add a description or issue link to this PR?
THX

**Comment by lherschi** [comment]
https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3715

**Comment by judovana** [comment]
The description will be duplicated with  content of https://icedtea.classpath.org/bugzilla/show_bug.cgi?id=3715 ; So links looks goof, until classapth bugzilla is obsolated. I would follow https://github.com/AdoptOpenJDK/icedtea-web/pull/8, but I do not have strong prefferences.

**Comment by judovana** [comment]
Waht is supposed to happen with this PR? If reopen, can it be accompanied by test?

**Comment by lherschi** [comment]
see new pull request:
https://github.com/AdoptOpenJDK/icedtea-web/pull/13

**Pull request closed without merging**
