### PR TITLE
Reduced number of threads spawned for downloading of resources. Speedup is aprox 200-300%

### PR DESCRIPTION
**Pull request by judovana**
For detailed results see: https://github.com/judovana/GenerateUnlimitedNumberOfJars
Lmited number of visible download bars
Added proeprties for backward compatibility and fortuning above
Originally by akaschen@redhat.com

### CODE REVIEW

**Comment by judovana** [comment]
When I look into the results, then it is obvious that ITW  2.0 have already change like this incorporated.
Thus my main reason for this review, is to try to align with 2.0 as much as possible.

**Comment by sclassen** [comment]
@judovana will merge this as it looks good.
Do you see something we should incorporate into the 2.x branch to gain some speedup there?

**Comment by judovana** [comment]
ITW.2.0 have already this patch inside - in sme or other form. See the results: https://github.com/judovana/GenerateUnlimitedNumberOfJars

Only idea was to maybe disuc the swithces. But most of them is nto necessary.


Is itw 2.0 also reducing the visible donwload bars in huge apps?

**Comment by judovana** [comment]
Will try to move it also to 1.7 , as it is used form time to time on some obscurer  systems.

**Pull request merged**
