### PR TITLE
Added embedded mode

### PR DESCRIPTION
**Pull request by judovana**
If itw is built in EMBEDDED mode, then it search for jre/jdk "where it is placed" right after java_home.
It is done by simple .., ../..
The search for libraries is then done in same way as for BUNDLED mode

### CODE REVIEW

**Comment by karianna** [comment]
@douph1 Can you also comment?  I've added you to the team

**Comment by judovana** [comment]
Well you use rust launchers in adopt's build o jdk with webstart, dont you?-)

**Comment by douph1** [comment]
yes only rust exe ( no .bat files )

**Comment by karianna** [comment]
@judovana can you add documentation as you suggested in the other PR?

**Pull request merged**
